# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-26 19:03
from __future__ import unicode_literals

from django.db import migrations, models
import django_countries.fields
import localflavor.us.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='EcommerceUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(help_text='Email address', max_length=255, unique=True, verbose_name='Email address')),
                ('first_name', models.CharField(help_text='First name', max_length=75, verbose_name='First name')),
                ('last_name', models.CharField(help_text='Last name', max_length=75, verbose_name='Last name')),
                ('phone_number', models.CharField(max_length=30, verbose_name='phone number')),
                ('date_joined', models.DateTimeField(auto_now=True, verbose_name='date joined')),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(blank=True, max_length=100, verbose_name='Business Name')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('address_1', models.CharField(max_length=100, verbose_name='Address Line 1')),
                ('address_2', models.CharField(blank=True, max_length=100, verbose_name='Address Line 2')),
                ('city', models.CharField(max_length=100, verbose_name='City')),
                ('state', localflavor.us.models.USStateField()),
                ('zip_code', localflavor.us.models.USZipCodeField()),
                ('country', django_countries.fields.CountryField(max_length=2)),
            ],
        ),
    ]
