# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-26 19:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ecommerceuser',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='ecommerceuser',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='ecommerceuser',
            name='user_permissions',
        ),
    ]
