# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-27 10:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20161027_0840'),
    ]

    operations = [
        migrations.AddField(
            model_name='ecommerceuser',
            name='company',
            field=models.CharField(blank=True, default='', help_text='Company info added by user upon registration', max_length=255),
        ),
    ]
