# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-27 13:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_activation'),
    ]

    operations = [
        migrations.AddField(
            model_name='ecommerceuser',
            name='idp_uuid',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='ecommerceuser',
            name='company',
            field=models.CharField(help_text='Company info added by user upon registration', max_length=255),
        ),
    ]
