# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-27 19:41
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_remove_ecommerceuser_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='primary_contact',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='account', to=settings.AUTH_USER_MODEL),
        ),
    ]
