# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-29 19:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_account_primary_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='phone_number',
            field=models.CharField(default='', help_text='Phone number', max_length=30, verbose_name='phone number'),
            preserve_default=False,
        ),
    ]
