# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-30 19:56
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_auto_20161030_1808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='primary_contact',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
