# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-02 16:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0017_auto_20161101_2216'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='credits_used',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
    ]
