# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-02 17:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0018_payment_credits_used'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='stripe_reference',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
