# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-05 21:27
from __future__ import unicode_literals

from django.db import migrations
import localflavor.us.models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0019_payment_stripe_reference'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='name',
        ),
        migrations.AlterField(
            model_name='account',
            name='state',
            field=localflavor.us.models.USStateField(blank=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='zip_code',
            field=localflavor.us.models.USZipCodeField(blank=True),
        ),
    ]
