# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-06 21:36
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0020_auto_20161105_2127'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='invoice_id',
            field=models.CharField(default=uuid.uuid4, max_length=100, unique=True),
        ),
    ]
