# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-14 10:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0021_payment_invoice_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='account',
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
