# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-15 17:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0023_auto_20161114_1655'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='payment_on_platform',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='ecommerceuser',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='billing_admins', to='account.Account'),
        ),
    ]
