# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-17 13:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0025_premiuminvitation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='premiuminvitation',
            name='activation_key',
            field=models.CharField(blank=True, max_length=40, verbose_name='activation key'),
        ),
    ]
