# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-21 21:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0026_auto_20161117_1304'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ecommerceuser',
            name='idp_uuid',
        ),
    ]
