# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-22 17:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0027_remove_ecommerceuser_idp_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ecommerceuser',
            name='username',
            field=models.CharField(blank=True, default='', max_length=75),
        ),
    ]
