# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-28 19:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0028_auto_20161122_1755'),
    ]

    operations = [
        migrations.AddField(
            model_name='ecommerceuser',
            name='idp_uuid',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
