# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-28 12:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Stripe_Customer',
            new_name='StripeCustomer',
        ),
    ]
