# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-28 12:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_auto_20161028_1247'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stripecustomer',
            old_name='primary_contact',
            new_name='account',
        ),
    ]
