# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-28 12:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_auto_20161028_1247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stripecustomer',
            name='account',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stripe', to='account.Account'),
        ),
    ]
