# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-31 19:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0005_stripecard'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stripecard',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='stripecard',
            name='last_4',
        ),
    ]
