# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-31 19:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0006_auto_20161031_1924'),
    ]

    operations = [
        migrations.AddField(
            model_name='stripecard',
            name='primary_card',
            field=models.BooleanField(default=True),
        ),
    ]
