# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-31 22:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0007_stripecard_primary_card'),
    ]

    operations = [
        migrations.AddField(
            model_name='stripecard',
            name='exp_month',
            field=models.IntegerField(default=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stripecard',
            name='exp_year',
            field=models.IntegerField(default=17),
            preserve_default=False,
        ),
    ]
