# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-01 09:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0008_auto_20161031_2223'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stripecard',
            old_name='primary_card',
            new_name='is_primary',
        ),
        migrations.RemoveField(
            model_name='stripecard',
            name='exp_month',
        ),
        migrations.RemoveField(
            model_name='stripecard',
            name='exp_year',
        ),
    ]
