# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-17 13:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0012_auto_20161114_1655'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='failed',
            field=models.BooleanField(default=False),
        ),
    ]
