# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-18 22:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0014_auto_20161117_2011'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='month',
            field=models.IntegerField(default=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='year',
            field=models.IntegerField(default=2016),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='payment',
            name='invoice_id',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
