# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-29 20:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gluu_license', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='license',
            name='license_password',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='license',
            name='public_key',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='license',
            name='public_password',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
