# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-29 20:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gluu_license', '0005_auto_20161029_2043'),
    ]

    operations = [
        migrations.AddField(
            model_name='license',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
