# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-29 20:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gluu_license', '0006_license_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='license',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='licenses', to='account.Account'),
        ),
    ]
