# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-30 11:00
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('gluu_license', '0007_auto_20161029_2052'),
    ]

    operations = [
        migrations.AddField(
            model_name='license',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 10, 30, 11, 0, 9, 695588, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='license',
            name='expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 10, 30, 11, 0, 13, 765237, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
