# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-30 18:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gluu_license', '0008_auto_20161030_1100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='license',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
