# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-01 19:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gluu_license', '0009_auto_20161030_1808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='license',
            name='account',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='license', to='account.Account'),
        ),
    ]
