# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-07 18:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('gluu_license', '0010_auto_20161101_1949'),
    ]

    operations = [
        migrations.CreateModel(
            name='LicenseRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paid', models.BooleanField(default=False)),
                ('number_licenses', models.IntegerField()),
                ('details', jsonfield.fields.JSONField(default=dict)),
                ('license', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='gluu_license.License')),
            ],
        ),
    ]
