# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-07 20:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gluu_license', '0011_licenserecord'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='licenserecord',
            name='paid',
        ),
        migrations.AddField(
            model_name='licenserecord',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='licenserecord',
            name='month',
            field=models.IntegerField(default=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='licenserecord',
            name='year',
            field=models.IntegerField(default=2015),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='license',
            name='license_id',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
