# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-14 11:42
from __future__ import unicode_literals

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('gluu_license', '0012_auto_20161107_2020'),
    ]

    operations = [
        migrations.AddField(
            model_name='licenserecord',
            name='paid_records',
            field=jsonfield.fields.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='licenserecord',
            name='payment_status',
            field=models.CharField(choices=[(b'UNPD', b'Unpaid'), (b'PAID', b'Paid'), (b'PART', b'Partially Paid')], default=b'UNPD', max_length=5),
        ),
    ]
