# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-14 12:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gluu_license', '0013_auto_20161114_1142'),
    ]

    operations = [
        migrations.RenameField(
            model_name='licenserecord',
            old_name='paid_records',
            new_name='paid_licenses',
        ),
    ]
