# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-14 16:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gluu_license', '0014_auto_20161114_1256'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='licenserecord',
            name='payment_status',
        ),
        migrations.AddField(
            model_name='licenserecord',
            name='fully_paid',
            field=models.BooleanField(default=False),
        ),
    ]
