# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-17 20:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gluu_license', '0015_auto_20161114_1627'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='licenserecord',
            name='fully_paid',
        ),
        migrations.RemoveField(
            model_name='licenserecord',
            name='paid_licenses',
        ),
    ]
