# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-24 19:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gluu_license', '0017_auto_20161124_1735'),
    ]

    operations = [
        migrations.AddField(
            model_name='license',
            name='is_blocked',
            field=models.BooleanField(default=False),
        ),
    ]
